name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_call:

jobs:
  esp-elf-gcc:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
      - name: Install prerequisites
        run: |
          sudo apt update -y
          sudo apt-get install -y bison build-essential ccache clang-format cmake dfu-util doxygen flex git gperf graphviz libbsd-dev libffi-dev libssl-dev libusb-1.0-0 ninja-build openjdk-21-jdk python3 python3-pip python3-venv ruby wget
      - name: Install ESP-IDF
        run: |
          mkdir -p ~/esp
          cd ~/esp
          git clone -b v5.5.1 --recursive https://github.com/espressif/esp-idf.git
          cd ~/esp/esp-idf
          ./install.sh esp32s3
      - run: |
          . $HOME/esp/esp-idf/export.sh
          cmake --preset "Release"
          cmake --build build --parallel --target FirmwareRelease
      - name: Find archive file
        run: |
          echo "ARTIFACT_NAME=$(find build -maxdepth 1 -type f -name "Firmware-*.zip" -printf "%f\n")" >> $GITHUB_ENV
          echo "ARTIFACT_PATH=$(find build -maxdepth 1 -type f -name "Firmware-*.zip")" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4.6.2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_PATH }}
