name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  esp-elf-gcc:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Install prerequisites
        run: |
          sudo apt update -y
          sudo apt-get install -y bison build-essential ccache clang-format cmake dfu-util doxygen flex git gperf graphviz libbsd-dev libffi-dev libssl-dev libusb-1.0-0 ninja-build openjdk-21-jdk python3 python3-pip python3-venv ruby wget
      - name: Install ESP-IDF
        run: |
          mkdir -p ~/esp
          cd ~/esp
          git clone -b fix_ws_recv --recursive https://github.com/higaski/esp-idf.git
          cd ~/esp/esp-idf
          ./install.sh esp32s3
      - run: |
          . $HOME/esp/esp-idf/export.sh
          cmake --preset "Release"
          cmake --build build --parallel
