name: tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    uses: ZIMO-Elektronik/.github-workflows/.github/workflows/esp-elf-gcc.yml@v0.0.9
    with:
      pre-build: |
        sudo apt update -y
        sudo apt install -y libbsd-dev ninja-build
      esp_idf_version: v5.5.0
      target: linux
      command: |
        cmake --preset "Tests"
        cmake --build build --parallel
      post-build: ./build/Firmware.elf
